[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
; python_functions = *Tests
; addopts = -v --strict-markers --tb=short
; markers =
;     lento: pruebas que tardan más tiempo en ejecutarse
;     regresion: pruebas importantes para detectar regresiones
;     config: pruebas relacionadas con configuración del proyecto
